require("rensoguilalas.plugins-setup")
require("rensoguilalas.core.options")
require("rensoguilalas.core.keymaps")
require("rensoguilalas.core.colorscheme")
require("rensoguilalas.plugins.comment")
require("rensoguilalas.plugins.nvim-tree")
require("rensoguilalas.plugins.lualine")
require("rensoguilalas.plugins.telescope")
require("rensoguilalas.plugins.nvim-cmp")
require("rensoguilalas.plugins.lsp.mason")
require("rensoguilalas.plugins.lsp.lspsaga")
require("rensoguilalas.plugins.lsp.lspconfig")
require("rensoguilalas.plugins.lsp.null-ls") -- the github got archieved, need to find a new formatting & linting plugin
require("rensoguilalas.plugins.autopairs")
require("rensoguilalas.plugins.treesitter")
require("rensoguilalas.plugins.gitsigns")
